import { PersonApiField } from '../interfaces/api-fields.interface';

export const personApiFields: PersonApiField[] = [
  {
    title: 'Identity',
    children: [
      { name: 'first_name', title: 'First Name' },
      { name: 'middle_initial', title: 'Middle Initial' },
      { name: 'last_name', title: 'Last Name' },
      { name: 'generational_suffix', title: 'Generational Suffix' },
      { name: 'gender', title: 'Gender' },
      { name: 'age', title: 'Age' },
      { name: 'date_of_birth', title: 'Date of Birth' },
      { name: 'estimated_date_of_birth', title: 'Estimated Date of Birth' },
    ],
  },
  {
    title: 'Contact',
    children: [
      {
        title: 'Emails',
        children: [
          { name: 'emails_count', title: 'Emails Count' },
          { name: 'emails.address', title: 'Email Address' },
          { name: 'emails.deliverable', title: 'Deliverable' },
          { name: 'emails.marketable', title: 'Marketable' },
        ],
      },
      {
        title: 'Cell Phones',
        children: [
          { name: 'cell_phones.phone', title: 'Phone' },
          { name: 'cell_phones.prepaid', title: 'Prepaid' },
          { name: 'cell_phones.active', title: 'Active'},
          { name: 'cell_phones.account_level', title: 'Account Level' },
        ],
      },
    ]
  },
  {
    title: 'Location',
    children: [
      { name: 'address_type', title: 'Address Type' },
      { name: 'state', title: 'State' },
      { name: 'city', title: 'City' },
      { name: 'street', title: 'Street' },
      { name: 'county_code', title: 'County Code' },
      { name: 'postal_code', title: 'Postal Code' },
      { name: 'geocoordinate', title: 'Geocoordinate' },
    ],
  },
  {
      title: 'Financial',
      children: [
          { name: 'family.estimated_income', title: 'Estimated Income' },
          { name: 'real_estate.estimated_home_value', title: 'Estimated Home Value' },
          { name: 'credit_card_types', title: 'Credit Card Types' },
          { name: 'socioeconomic_status', title: 'Socioeconomic Status' },
      ]
  },
  {
    title: 'Family',
    children: [
        { name: 'estimated_married', title: 'Estimated Married' },
        { name: 'estimated_head_of_family', title: 'Estimated Head of Family' },
        { name: 'family.adult_count', title: 'Adults in Household' },
        { name: 'family.home_owner', title: 'Home Owner' },
        { name: 'family.estimated_has_children', title: 'Estimated Has Children' },
        { name: 'children_count', title: 'Children Count' },
        { name: 'children.age', title: 'Child Age' },
        { name: 'children.gender', title: 'Child Gender' },
    ]
  },
  {
    title: 'Politics',
    children: [
      { name: 'political_party_affiliation', title: 'Political Affiliation' },
      { name: 'registered_voter', title: 'Registered Voter' },
    ]
  },
  {
    title: 'Culture',
    children: [
      { name: 'estimated_country_of_origin', title: 'Estimated Country of Origin' },
      { name: 'estimated_ethnicity', title: 'Estimated Ethnicity' },
      { name: 'estimated_ethnic_group', title: 'Estimated Ethnic Group' },
      { name: 'estimated_language', title: 'Estimated Language' },
      { name: 'estimated_primary_language', title: 'Estimated Primary Language' },
      { name: 'estimated_religious_affiliation', title: 'Estimated Religious Affiliation' },
    ]
  },
  {
      title: 'Interests',
      children: [
          { name: 'interests.accessories', title: 'Accessories' },
          { name: 'interests.american_history', title: 'American History' },
          { name: 'interests.auto_racing', title: 'Auto Racing' },
          { name: 'interests.aviation', title: 'Aviation' },
          { name: 'interests.bargains', title: 'Bargains' },
          { name: 'interests.baseball', title: 'Baseball' },
          { name: 'interests.basketball', title: 'Basketball' },
          { name: 'interests.boating_sailing', title: 'Boating/Sailing' },
          { name: 'interests.books', title: 'Books' },
          { name: 'interests.camping', title: 'Camping' },
          { name: 'interests.cats', title: 'Cats' },
          { name: 'interests.charities', title: 'Charities' },
          { name: 'interests.collectibles', title: 'Collectibles' },
          { name: 'interests.computers', title: 'Computers' },
          { name: 'interests.conservative_politics', title: 'Conservative Politics' },
          { name: 'interests.cooking', title: 'Cooking' },
          { name: 'interests.crafts', title: 'Crafts' },
          { name: 'interests.credit_cards', title: 'Credit Cards' },
          { name: 'interests.cruises', title: 'Cruises' },
          { name: 'interests.dieting', title: 'Dieting' },
          { name: 'interests.diy', title: 'DIY' },
          { name: 'interests.dogs', title: 'Dogs' },
          { name: 'interests.electronics', title: 'Electronics' },
          { name: 'interests.family', title: 'Family' },
          { name: 'interests.fishing', title: 'Fishing' },
          { name: 'interests.fitness', title: 'Fitness' },
          { name: 'interests.football', title: 'Football' },
          { name: 'interests.gambling', title: 'Gambling' },
          { name: 'interests.games', title: 'Games' },
          { name: 'interests.gardening', title: 'Gardening' },
          { name: 'interests.golf', title: 'Golf' },
          { name: 'interests.gourmet_foods', title: 'Gourmet Foods' },
          { name: 'interests.health', title: 'Health' },
          { name: 'interests.history', title: 'History' },
          { name: 'interests.hobbies', title: 'Hobbies' },
          { name: 'interests.home_decor', title: 'Home Decor' },
          { name: 'interests.hunting', title: 'Hunting' },
          { name: 'interests.internet', title: 'Internet' },
          { name: 'interests.liberal_politics', title: 'Liberal Politics' },
          { name: 'interests.mens_apparel', title: "Men's Apparel" },
          { name: 'interests.motorcycles', title: 'Motorcycles' },
          { name: 'interests.music', title: 'Music' },
          { name: 'interests.outdoors', title: 'Outdoors' },
          { name: 'interests.pets', title: 'Pets' },
          { name: 'interests.photography', title: 'Photography' },
          { name: 'interests.politics', title: 'Politics' },
          { name: 'interests.religion', title: 'Religion' },
          { name: 'interests.womens_apparel', title: "Women's Apparel" },
          { name: 'interests.african_american_products', title: 'African American Products' },
          { name: 'interests.asian_products', title: 'Asian Products' },
          { name: 'interests.beaches', title: 'Beaches' },
          { name: 'interests.birds', title: 'Birds' },
          { name: 'interests.business', title: 'Business' },
          { name: 'interests.cars', title: 'Cars' },
          { name: 'interests.catalogs', title: 'Catalogs' },
          { name: 'interests.childrens_apparel', title: "Children's Apparel" },
          { name: 'interests.college', title: 'College' },
          { name: 'interests.comics', title: 'Comics' },
          { name: 'interests.cosmetics', title: 'Cosmetics' },
          { name: 'interests.crocheting', title: 'Crocheting' },
          { name: 'interests.culture_arts', title: 'Culture & Arts' },
          { name: 'interests.current_events', title: 'Current Events' },
          { name: 'interests.domestic_travel', title: 'Domestic Travel' },
          { name: 'interests.farming', title: 'Farming' },
          { name: 'interests.fiction', title: 'Fiction' },
          { name: 'interests.gifts', title: 'Gifts' },
          { name: 'interests.hispanic_products', title: 'Hispanic Products' },
          { name: 'interests.hockey', title: 'Hockey' },
          { name: 'interests.home_office_products', title: 'Home Office Products' },
          { name: 'interests.horses', title: 'Horses' },
          { name: 'interests.inspirational_products', title: 'Inspirational Products' },
          { name: 'interests.knitting', title: 'Knitting' },
          { name: 'interests.magazines', title: 'Magazines' },
          { name: 'interests.mens_fashion', title: "Men's Fashion" },
          { name: 'interests.moneymaking_opportunities', title: 'Moneymaking Opportunities' },
          { name: 'interests.needlepoint', title: 'Needlepoint' },
          { name: 'interests.nonfiction', title: 'Nonfiction' },
          { name: 'interests.personal_finance', title: 'Personal Finance' },
          { name: 'interests.personalized_products', title: 'Personalized Products' },
          { name: 'interests.quilting', title: 'Quilting' },
          { name: 'interests.rvs', title: 'RVs' },
          { name: 'interests.science', title: 'Science' },
          { name: 'interests.science_fiction', title: 'Science Fiction' },
          { name: 'interests.senior_products', title: 'Senior Products' },
          { name: 'interests.sewing', title: 'Sewing' },
          { name: 'interests.skiing', title: 'Skiing' },
          { name: 'interests.soccer', title: 'Soccer' },
          { name: 'interests.stationery', title: 'Stationery' },
          { name: 'interests.sweepstakes', title: 'Sweepstakes' },
          { name: 'interests.technology', title: 'Technology' },
          { name: 'interests.tennis', title: 'Tennis' },
          { name: 'interests.tobacco', title: 'Tobacco' },
          { name: 'interests.trucks', title: 'Trucks' },
          { name: 'interests.tv_movies', title: 'TV & Movies' },
          { name: 'interests.wildlife', title: 'Wildlife' },
          { name: 'interests.womens_fashion', title: "Women's Fashion" }
      ]
  },
  {
    title: 'Digital',
    children: [
      { name: 'digital_platforms', title: 'Digital Platforms' }
    ]
  }
];

export const personApiLimit: number = 10;